export { default as user_icon } from './person-fill.svg' ;
export { default as password_icon } from './lock-fill.svg' ;
export { default as axa_Picture } from './AXA.svg' ;
export { default as facebook_icon } from './facebook.svg' ;
export { default as axa_Logo } from './axa-logo-white.png' ;
export { default as bi_house_fill } from './house-fill.svg' ;
export { default as contact_icon } from './headset.svg' ;
export { default as Poster_1} from './axa_affiche_1.jfif' ;
export { default as Poster_2} from './axa_affiche_2.jpeg' ;
export { default as Poster_3} from './axa_affiche_3.jpeg';
export { default as Poster_4} from './axa_affiche_4.avif';
export { default as Poster_5} from './axa_affiche_5.png';
export { default as Poster_6} from './axa_affiche_6.jpeg';
export { default as Poster_7} from './axa_affiche_7.jpeg';
export { default as Poster_8} from './axa_affiche_8.jpeg';
export { default as left_icon } from './left_icon.svg' ;
export { default as right_icon } from './right_icon.svg' ;
export { default as telephone_icon } from './telephone_icon.svg' ;
export { default as google_icon } from './gmail_icon.svg' ;
export { default as instagram_icon } from './instagram_icon.svg'
export { default as whatsapp_icon } from './whatsapp_icon.svg';
export { default as Poster_9 } from './axa_affiche_9.jpeg';
export { default as Poster_10 } from './axa_affiche_10.jpeg' ;
export { default as Poster_11 } from './axa_affiche_11.jpeg' ;
export { default as Poster_12 } from './axa_affiche_12.jpeg' ;
export { default as Poster_13 } from './axa_affiche_13.jpeg' ;
export { default as Poster_14 } from './axa_affiche_14.jpeg' ;
export { default as crached_car_icon } from './minor_crash_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24.svg' ;
export { default as protection_icon } from './verified_user_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24.svg' ;
export { default as breakdown_car_icon } from './auto_towing_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24.svg' ;
export { default as add_icon} from './add_icon.svg' ;
export { default as star_icon } from './star_icon.svg' ;
export { default as car_icon } from './car_icon.svg' ;
export { default as bicykle_icon } from './bicycle_icon.svg' ;
export { default as tractors_icon } from './agriculture_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24.svg' ;
export { default as down_icon } from './arrow-down-circle-fill.svg' ;
export { default as up_icon } from './arrow-up-circle-fill.svg' ;
export { default as truck_icon } from './local_shipping_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24.svg' ; 
export { default as card_icon } from './credit_card_clock_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24.svg' ;
export { default as close_icon} from './close_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24.svg' ;
export { default as animation_1 } from './animation_1.gif' ;
export { default as animation_2 } from './output-onlinegiftools (1).gif' ;
export { default as next_icon } from './play_arrow_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24.svg' ;
export { default as prev_icon } from './arrow_back_2_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24.svg' ;
export { default as masterCard_icon} from './MasterCard_Logo.jpeg' ;
export { default as visa_icon } from './VISA_Logo.jpeg' ;
export { default as paypal_icon } from './Paypal.jpeg' ;
export { default as cashOnDelivery} from './CashOnDelivry.png' ;
export { default as chatbot_icon } from './chatbot.png' ;
export { default as user_3d_icon} from './3d_icon.jpeg';